[2025-02-08T19:03:16.523+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-08T19:03:16.535+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2025-01-23T00:00:00+00:00 [queued]>
[2025-02-08T19:03:16.543+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2025-01-23T00:00:00+00:00 [queued]>
[2025-02-08T19:03:16.544+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-02-08T19:03:16.559+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): generate_customer_dim_data> on 2025-01-23 00:00:00+00:00
[2025-02-08T19:03:16.568+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2079) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-08T19:03:16.569+0000] {standard_task_runner.py:72} INFO - Started process 2093 to run task
[2025-02-08T19:03:16.568+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'customer_dim_generator', 'generate_customer_dim_data', 'scheduled__2025-01-23T00:00:00+00:00', '--job-id', '372', '--raw', '--subdir', 'DAGS_FOLDER/customer_dim_gen.py', '--cfg-path', '/tmp/tmpimsvrxqd']
[2025-02-08T19:03:16.575+0000] {standard_task_runner.py:105} INFO - Job 372: Subtask generate_customer_dim_data
[2025-02-08T19:03:16.613+0000] {task_command.py:467} INFO - Running <TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2025-01-23T00:00:00+00:00 [running]> on host 2c1cd59afcc0
[2025-02-08T19:03:16.695+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Saleh' AIRFLOW_CTX_DAG_ID='customer_dim_generator' AIRFLOW_CTX_TASK_ID='generate_customer_dim_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-23T00:00:00+00:00'
[2025-02-08T19:03:16.697+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-08T19:03:16.719+0000] {logging_mixin.py:190} INFO - CSV file './customer_dim_large_data.csv' with 100 rows has been generated successfully.
[2025-02-08T19:03:16.719+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-08T19:03:16.727+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-08T19:03:16.727+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=customer_dim_generator, task_id=generate_customer_dim_data, run_id=scheduled__2025-01-23T00:00:00+00:00, execution_date=20250123T000000, start_date=20250208T190316, end_date=20250208T190316
[2025-02-08T19:03:16.789+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-08T19:03:16.804+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-08T19:03:16.819+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-08T20:43:48.361+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-08T20:43:48.381+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2025-01-23T00:00:00+00:00 [queued]>
[2025-02-08T20:43:48.390+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2025-01-23T00:00:00+00:00 [queued]>
[2025-02-08T20:43:48.391+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-02-08T20:43:48.408+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): generate_customer_dim_data> on 2025-01-23 00:00:00+00:00
[2025-02-08T20:43:48.418+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=858) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-08T20:43:48.421+0000] {standard_task_runner.py:72} INFO - Started process 875 to run task
[2025-02-08T20:43:48.419+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'customer_dim_generator', 'generate_customer_dim_data', 'scheduled__2025-01-23T00:00:00+00:00', '--job-id', '513', '--raw', '--subdir', 'DAGS_FOLDER/customer_dim_gen.py', '--cfg-path', '/tmp/tmpxsq9uoeo']
[2025-02-08T20:43:48.423+0000] {standard_task_runner.py:105} INFO - Job 513: Subtask generate_customer_dim_data
[2025-02-08T20:43:48.471+0000] {task_command.py:467} INFO - Running <TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2025-01-23T00:00:00+00:00 [running]> on host 86932746817d
[2025-02-08T20:43:48.560+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Saleh' AIRFLOW_CTX_DAG_ID='customer_dim_generator' AIRFLOW_CTX_TASK_ID='generate_customer_dim_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-23T00:00:00+00:00'
[2025-02-08T20:43:48.562+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-08T20:43:48.586+0000] {logging_mixin.py:190} INFO - CSV file './customer_dim_large_data.csv' with 100 rows has been generated successfully.
[2025-02-08T20:43:48.587+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-08T20:43:48.598+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-08T20:43:48.598+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=customer_dim_generator, task_id=generate_customer_dim_data, run_id=scheduled__2025-01-23T00:00:00+00:00, execution_date=20250123T000000, start_date=20250208T204348, end_date=20250208T204348
[2025-02-08T20:43:48.637+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-08T20:43:48.648+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
