[2025-02-08T19:02:06.520+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-08T19:02:06.545+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2024-10-17T00:00:00+00:00 [queued]>
[2025-02-08T19:02:06.560+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2024-10-17T00:00:00+00:00 [queued]>
[2025-02-08T19:02:06.564+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-02-08T19:02:06.580+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): generate_customer_dim_data> on 2024-10-17 00:00:00+00:00
[2025-02-08T19:02:06.593+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1199) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-08T19:02:06.594+0000] {standard_task_runner.py:72} INFO - Started process 1247 to run task
[2025-02-08T19:02:06.593+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'customer_dim_generator', 'generate_customer_dim_data', 'scheduled__2024-10-17T00:00:00+00:00', '--job-id', '172', '--raw', '--subdir', 'DAGS_FOLDER/customer_dim_gen.py', '--cfg-path', '/tmp/tmpmpmypjy4']
[2025-02-08T19:02:06.601+0000] {standard_task_runner.py:105} INFO - Job 172: Subtask generate_customer_dim_data
[2025-02-08T19:02:06.678+0000] {task_command.py:467} INFO - Running <TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2024-10-17T00:00:00+00:00 [running]> on host 2c1cd59afcc0
[2025-02-08T19:02:06.818+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Saleh' AIRFLOW_CTX_DAG_ID='customer_dim_generator' AIRFLOW_CTX_TASK_ID='generate_customer_dim_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-17T00:00:00+00:00'
[2025-02-08T19:02:06.824+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-08T19:02:06.854+0000] {logging_mixin.py:190} INFO - CSV file './customer_dim_large_data.csv' with 100 rows has been generated successfully.
[2025-02-08T19:02:06.857+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-08T19:02:06.874+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-08T19:02:06.875+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=customer_dim_generator, task_id=generate_customer_dim_data, run_id=scheduled__2024-10-17T00:00:00+00:00, execution_date=20241017T000000, start_date=20250208T190206, end_date=20250208T190206
[2025-02-08T19:02:06.944+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-08T19:02:06.963+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-08T19:02:06.967+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-08T20:39:44.708+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-08T20:39:44.739+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2024-10-17T00:00:00+00:00 [queued]>
[2025-02-08T20:39:44.755+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2024-10-17T00:00:00+00:00 [queued]>
[2025-02-08T20:39:44.756+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-02-08T20:39:44.797+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): generate_customer_dim_data> on 2024-10-17 00:00:00+00:00
[2025-02-08T20:39:44.821+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=731) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-08T20:39:44.824+0000] {standard_task_runner.py:72} INFO - Started process 758 to run task
[2025-02-08T20:39:44.816+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'customer_dim_generator', 'generate_customer_dim_data', 'scheduled__2024-10-17T00:00:00+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/customer_dim_gen.py', '--cfg-path', '/tmp/tmp14902yiv']
[2025-02-08T20:39:44.840+0000] {standard_task_runner.py:105} INFO - Job 38: Subtask generate_customer_dim_data
[2025-02-08T20:39:44.953+0000] {task_command.py:467} INFO - Running <TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2024-10-17T00:00:00+00:00 [running]> on host 7e959c1a2a8b
[2025-02-08T20:39:45.104+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Saleh' AIRFLOW_CTX_DAG_ID='customer_dim_generator' AIRFLOW_CTX_TASK_ID='generate_customer_dim_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-17T00:00:00+00:00'
[2025-02-08T20:39:45.106+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-08T20:39:45.150+0000] {logging_mixin.py:190} INFO - CSV file './customer_dim_large_data.csv' with 100 rows has been generated successfully.
[2025-02-08T20:39:45.152+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-08T20:39:45.160+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-08T20:39:45.162+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=customer_dim_generator, task_id=generate_customer_dim_data, run_id=scheduled__2024-10-17T00:00:00+00:00, execution_date=20241017T000000, start_date=20250208T203944, end_date=20250208T203945
[2025-02-08T20:39:45.211+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-08T20:39:45.240+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-08T20:39:45.256+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-08T20:42:51.408+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-08T20:42:51.427+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2024-10-17T00:00:00+00:00 [queued]>
[2025-02-08T20:42:51.437+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2024-10-17T00:00:00+00:00 [queued]>
[2025-02-08T20:42:51.437+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-02-08T20:42:51.454+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): generate_customer_dim_data> on 2024-10-17 00:00:00+00:00
[2025-02-08T20:42:51.464+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=417) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-08T20:42:51.463+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'customer_dim_generator', 'generate_customer_dim_data', 'scheduled__2024-10-17T00:00:00+00:00', '--job-id', '415', '--raw', '--subdir', 'DAGS_FOLDER/customer_dim_gen.py', '--cfg-path', '/tmp/tmpouc1un9d']
[2025-02-08T20:42:51.466+0000] {standard_task_runner.py:72} INFO - Started process 437 to run task
[2025-02-08T20:42:51.467+0000] {standard_task_runner.py:105} INFO - Job 415: Subtask generate_customer_dim_data
[2025-02-08T20:42:51.529+0000] {task_command.py:467} INFO - Running <TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2024-10-17T00:00:00+00:00 [running]> on host 86932746817d
[2025-02-08T20:42:51.631+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Saleh' AIRFLOW_CTX_DAG_ID='customer_dim_generator' AIRFLOW_CTX_TASK_ID='generate_customer_dim_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-17T00:00:00+00:00'
[2025-02-08T20:42:51.633+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-08T20:42:51.657+0000] {logging_mixin.py:190} INFO - CSV file './customer_dim_large_data.csv' with 100 rows has been generated successfully.
[2025-02-08T20:42:51.658+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-08T20:42:51.667+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-08T20:42:51.668+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=customer_dim_generator, task_id=generate_customer_dim_data, run_id=scheduled__2024-10-17T00:00:00+00:00, execution_date=20241017T000000, start_date=20250208T204251, end_date=20250208T204251
[2025-02-08T20:42:51.722+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-08T20:42:51.743+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-08T20:42:51.750+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
