[2025-02-08T19:03:15.704+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-08T19:03:15.731+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2025-01-20T00:00:00+00:00 [queued]>
[2025-02-08T19:03:15.751+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2025-01-20T00:00:00+00:00 [queued]>
[2025-02-08T19:03:15.753+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-02-08T19:03:15.787+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): generate_customer_dim_data> on 2025-01-20 00:00:00+00:00
[2025-02-08T19:03:15.800+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2051) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-08T19:03:15.801+0000] {standard_task_runner.py:72} INFO - Started process 2077 to run task
[2025-02-08T19:03:15.800+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'customer_dim_generator', 'generate_customer_dim_data', 'scheduled__2025-01-20T00:00:00+00:00', '--job-id', '367', '--raw', '--subdir', 'DAGS_FOLDER/customer_dim_gen.py', '--cfg-path', '/tmp/tmp4k_5gkr3']
[2025-02-08T19:03:15.804+0000] {standard_task_runner.py:105} INFO - Job 367: Subtask generate_customer_dim_data
[2025-02-08T19:03:15.878+0000] {task_command.py:467} INFO - Running <TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2025-01-20T00:00:00+00:00 [running]> on host 2c1cd59afcc0
[2025-02-08T19:03:16.018+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Saleh' AIRFLOW_CTX_DAG_ID='customer_dim_generator' AIRFLOW_CTX_TASK_ID='generate_customer_dim_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-20T00:00:00+00:00'
[2025-02-08T19:03:16.019+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-08T19:03:16.041+0000] {logging_mixin.py:190} INFO - CSV file './customer_dim_large_data.csv' with 100 rows has been generated successfully.
[2025-02-08T19:03:16.041+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-08T19:03:16.050+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-08T19:03:16.051+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=customer_dim_generator, task_id=generate_customer_dim_data, run_id=scheduled__2025-01-20T00:00:00+00:00, execution_date=20250120T000000, start_date=20250208T190315, end_date=20250208T190316
[2025-02-08T19:03:16.102+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-08T19:03:16.121+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-08T19:03:16.127+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-08T20:41:03.301+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-08T20:41:03.318+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2025-01-20T00:00:00+00:00 [queued]>
[2025-02-08T20:41:03.331+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2025-01-20T00:00:00+00:00 [queued]>
[2025-02-08T20:41:03.331+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-02-08T20:41:03.349+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): generate_customer_dim_data> on 2025-01-20 00:00:00+00:00
[2025-02-08T20:41:03.360+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1910) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-08T20:41:03.361+0000] {standard_task_runner.py:72} INFO - Started process 1934 to run task
[2025-02-08T20:41:03.369+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'customer_dim_generator', 'generate_customer_dim_data', 'scheduled__2025-01-20T00:00:00+00:00', '--job-id', '319', '--raw', '--subdir', 'DAGS_FOLDER/customer_dim_gen.py', '--cfg-path', '/tmp/tmpf49y6bhb']
[2025-02-08T20:41:03.371+0000] {standard_task_runner.py:105} INFO - Job 319: Subtask generate_customer_dim_data
[2025-02-08T20:41:03.423+0000] {task_command.py:467} INFO - Running <TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2025-01-20T00:00:00+00:00 [running]> on host 7e959c1a2a8b
[2025-02-08T20:41:03.533+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Saleh' AIRFLOW_CTX_DAG_ID='customer_dim_generator' AIRFLOW_CTX_TASK_ID='generate_customer_dim_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-20T00:00:00+00:00'
[2025-02-08T20:41:03.534+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-08T20:41:03.557+0000] {logging_mixin.py:190} INFO - CSV file './customer_dim_large_data.csv' with 100 rows has been generated successfully.
[2025-02-08T20:41:03.558+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-08T20:41:03.567+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-08T20:41:03.567+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=customer_dim_generator, task_id=generate_customer_dim_data, run_id=scheduled__2025-01-20T00:00:00+00:00, execution_date=20250120T000000, start_date=20250208T204103, end_date=20250208T204103
[2025-02-08T20:41:03.591+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-08T20:41:03.606+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-08T20:41:03.609+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-08T20:43:47.990+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-08T20:43:48.009+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2025-01-20T00:00:00+00:00 [queued]>
[2025-02-08T20:43:48.019+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2025-01-20T00:00:00+00:00 [queued]>
[2025-02-08T20:43:48.020+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-02-08T20:43:48.153+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): generate_customer_dim_data> on 2025-01-20 00:00:00+00:00
[2025-02-08T20:43:48.166+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=852) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-08T20:43:48.164+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'customer_dim_generator', 'generate_customer_dim_data', 'scheduled__2025-01-20T00:00:00+00:00', '--job-id', '510', '--raw', '--subdir', 'DAGS_FOLDER/customer_dim_gen.py', '--cfg-path', '/tmp/tmpqkijqmv8']
[2025-02-08T20:43:48.168+0000] {standard_task_runner.py:105} INFO - Job 510: Subtask generate_customer_dim_data
[2025-02-08T20:43:48.167+0000] {standard_task_runner.py:72} INFO - Started process 866 to run task
[2025-02-08T20:43:48.230+0000] {task_command.py:467} INFO - Running <TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2025-01-20T00:00:00+00:00 [running]> on host 86932746817d
[2025-02-08T20:43:48.345+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Saleh' AIRFLOW_CTX_DAG_ID='customer_dim_generator' AIRFLOW_CTX_TASK_ID='generate_customer_dim_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-20T00:00:00+00:00'
[2025-02-08T20:43:48.346+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-08T20:43:48.370+0000] {logging_mixin.py:190} INFO - CSV file './customer_dim_large_data.csv' with 100 rows has been generated successfully.
[2025-02-08T20:43:48.371+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-08T20:43:48.381+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-08T20:43:48.381+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=customer_dim_generator, task_id=generate_customer_dim_data, run_id=scheduled__2025-01-20T00:00:00+00:00, execution_date=20250120T000000, start_date=20250208T204348, end_date=20250208T204348
[2025-02-08T20:43:48.431+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-08T20:43:48.441+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
