[2025-02-08T19:00:11.245+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-08T19:00:11.262+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: account_dim_gen.generate_account_dim_data scheduled__2024-10-02T00:00:00+00:00 [queued]>
[2025-02-08T19:00:11.271+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: account_dim_gen.generate_account_dim_data scheduled__2024-10-02T00:00:00+00:00 [queued]>
[2025-02-08T19:00:11.272+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-02-08T19:00:11.290+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): generate_account_dim_data> on 2024-10-02 00:00:00+00:00
[2025-02-08T19:00:11.303+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'account_dim_gen', 'generate_account_dim_data', 'scheduled__2024-10-02T00:00:00+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/account_dim_gen.py', '--cfg-path', '/tmp/tmp7nzysrgc']
[2025-02-08T19:00:11.305+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=553) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-08T19:00:11.306+0000] {standard_task_runner.py:105} INFO - Job 28: Subtask generate_account_dim_data
[2025-02-08T19:00:11.306+0000] {standard_task_runner.py:72} INFO - Started process 575 to run task
[2025-02-08T19:00:11.402+0000] {task_command.py:467} INFO - Running <TaskInstance: account_dim_gen.generate_account_dim_data scheduled__2024-10-02T00:00:00+00:00 [running]> on host 2c1cd59afcc0
[2025-02-08T19:00:11.569+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Saleh' AIRFLOW_CTX_DAG_ID='account_dim_gen' AIRFLOW_CTX_TASK_ID='generate_account_dim_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-02T00:00:00+00:00'
[2025-02-08T19:00:11.571+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-08T19:00:11.591+0000] {logging_mixin.py:190} INFO - CSV file ./account_dim_large_data.csv with 50 row has been generated successfully!
[2025-02-08T19:00:11.591+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-08T19:00:11.598+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-08T19:00:11.599+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=account_dim_gen, task_id=generate_account_dim_data, run_id=scheduled__2024-10-02T00:00:00+00:00, execution_date=20241002T000000, start_date=20250208T190011, end_date=20250208T190011
[2025-02-08T19:00:11.706+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-08T19:00:11.722+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-08T19:00:11.905+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-08T20:39:51.798+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-08T20:39:51.816+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: account_dim_gen.generate_account_dim_data scheduled__2024-10-02T00:00:00+00:00 [queued]>
[2025-02-08T20:39:51.828+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: account_dim_gen.generate_account_dim_data scheduled__2024-10-02T00:00:00+00:00 [queued]>
[2025-02-08T20:39:51.828+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-02-08T20:39:51.844+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): generate_account_dim_data> on 2024-10-02 00:00:00+00:00
[2025-02-08T20:39:51.856+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=801) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-08T20:39:51.857+0000] {standard_task_runner.py:72} INFO - Started process 827 to run task
[2025-02-08T20:39:51.863+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'account_dim_gen', 'generate_account_dim_data', 'scheduled__2024-10-02T00:00:00+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/account_dim_gen.py', '--cfg-path', '/tmp/tmpn46khnew']
[2025-02-08T20:39:51.865+0000] {standard_task_runner.py:105} INFO - Job 56: Subtask generate_account_dim_data
[2025-02-08T20:39:51.961+0000] {task_command.py:467} INFO - Running <TaskInstance: account_dim_gen.generate_account_dim_data scheduled__2024-10-02T00:00:00+00:00 [running]> on host 7e959c1a2a8b
[2025-02-08T20:39:52.062+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Saleh' AIRFLOW_CTX_DAG_ID='account_dim_gen' AIRFLOW_CTX_TASK_ID='generate_account_dim_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-02T00:00:00+00:00'
[2025-02-08T20:39:52.065+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-08T20:39:52.090+0000] {logging_mixin.py:190} INFO - CSV file ./account_dim_large_data.csv with 50 row has been generated successfully!
[2025-02-08T20:39:52.090+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-08T20:39:52.100+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-08T20:39:52.101+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=account_dim_gen, task_id=generate_account_dim_data, run_id=scheduled__2024-10-02T00:00:00+00:00, execution_date=20241002T000000, start_date=20250208T203951, end_date=20250208T203952
[2025-02-08T20:39:52.154+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-08T20:39:52.180+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
