[2025-02-08T19:00:18.393+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-08T19:00:18.404+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: account_dim_gen.generate_account_dim_data scheduled__2024-10-17T00:00:00+00:00 [queued]>
[2025-02-08T19:00:18.413+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: account_dim_gen.generate_account_dim_data scheduled__2024-10-17T00:00:00+00:00 [queued]>
[2025-02-08T19:00:18.429+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-02-08T19:00:18.446+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): generate_account_dim_data> on 2024-10-17 00:00:00+00:00
[2025-02-08T19:00:18.454+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=619) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-08T19:00:18.455+0000] {standard_task_runner.py:72} INFO - Started process 633 to run task
[2025-02-08T19:00:18.454+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'account_dim_gen', 'generate_account_dim_data', 'scheduled__2024-10-17T00:00:00+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/account_dim_gen.py', '--cfg-path', '/tmp/tmpmmey0lkn']
[2025-02-08T19:00:18.457+0000] {standard_task_runner.py:105} INFO - Job 41: Subtask generate_account_dim_data
[2025-02-08T19:00:18.514+0000] {task_command.py:467} INFO - Running <TaskInstance: account_dim_gen.generate_account_dim_data scheduled__2024-10-17T00:00:00+00:00 [running]> on host 2c1cd59afcc0
[2025-02-08T19:00:18.782+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Saleh' AIRFLOW_CTX_DAG_ID='account_dim_gen' AIRFLOW_CTX_TASK_ID='generate_account_dim_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-17T00:00:00+00:00'
[2025-02-08T19:00:18.784+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-08T19:00:18.807+0000] {logging_mixin.py:190} INFO - CSV file ./account_dim_large_data.csv with 50 row has been generated successfully!
[2025-02-08T19:00:18.807+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-08T19:00:18.815+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-08T19:00:18.815+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=account_dim_gen, task_id=generate_account_dim_data, run_id=scheduled__2024-10-17T00:00:00+00:00, execution_date=20241017T000000, start_date=20250208T190018, end_date=20250208T190018
[2025-02-08T19:00:18.870+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-08T19:00:18.879+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-08T20:40:05.904+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-08T20:40:05.942+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: account_dim_gen.generate_account_dim_data scheduled__2024-10-17T00:00:00+00:00 [queued]>
[2025-02-08T20:40:05.954+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: account_dim_gen.generate_account_dim_data scheduled__2024-10-17T00:00:00+00:00 [queued]>
[2025-02-08T20:40:05.957+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-02-08T20:40:05.984+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): generate_account_dim_data> on 2024-10-17 00:00:00+00:00
[2025-02-08T20:40:06.007+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=982) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-08T20:40:06.013+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'account_dim_gen', 'generate_account_dim_data', 'scheduled__2024-10-17T00:00:00+00:00', '--job-id', '99', '--raw', '--subdir', 'DAGS_FOLDER/account_dim_gen.py', '--cfg-path', '/tmp/tmpb5np2zzy']
[2025-02-08T20:40:06.016+0000] {standard_task_runner.py:72} INFO - Started process 1005 to run task
[2025-02-08T20:40:06.018+0000] {standard_task_runner.py:105} INFO - Job 99: Subtask generate_account_dim_data
[2025-02-08T20:40:06.084+0000] {task_command.py:467} INFO - Running <TaskInstance: account_dim_gen.generate_account_dim_data scheduled__2024-10-17T00:00:00+00:00 [running]> on host 7e959c1a2a8b
[2025-02-08T20:40:06.265+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Saleh' AIRFLOW_CTX_DAG_ID='account_dim_gen' AIRFLOW_CTX_TASK_ID='generate_account_dim_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-17T00:00:00+00:00'
[2025-02-08T20:40:06.268+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-08T20:40:06.292+0000] {logging_mixin.py:190} INFO - CSV file ./account_dim_large_data.csv with 50 row has been generated successfully!
[2025-02-08T20:40:06.296+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-08T20:40:06.313+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-08T20:40:06.314+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=account_dim_gen, task_id=generate_account_dim_data, run_id=scheduled__2024-10-17T00:00:00+00:00, execution_date=20241017T000000, start_date=20250208T204005, end_date=20250208T204006
[2025-02-08T20:40:06.406+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-08T20:40:06.436+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-08T20:40:06.442+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
