[2025-02-08T19:00:51.926+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-08T19:00:51.943+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: account_dim_gen.generate_account_dim_data scheduled__2024-12-17T00:00:00+00:00 [queued]>
[2025-02-08T19:00:51.952+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: account_dim_gen.generate_account_dim_data scheduled__2024-12-17T00:00:00+00:00 [queued]>
[2025-02-08T19:00:51.953+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-02-08T19:00:51.972+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): generate_account_dim_data> on 2024-12-17 00:00:00+00:00
[2025-02-08T19:00:51.981+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=883) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-08T19:00:51.982+0000] {standard_task_runner.py:72} INFO - Started process 903 to run task
[2025-02-08T19:00:51.981+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'account_dim_gen', 'generate_account_dim_data', 'scheduled__2024-12-17T00:00:00+00:00', '--job-id', '102', '--raw', '--subdir', 'DAGS_FOLDER/account_dim_gen.py', '--cfg-path', '/tmp/tmpbh9lj63y']
[2025-02-08T19:00:51.983+0000] {standard_task_runner.py:105} INFO - Job 102: Subtask generate_account_dim_data
[2025-02-08T19:00:52.028+0000] {task_command.py:467} INFO - Running <TaskInstance: account_dim_gen.generate_account_dim_data scheduled__2024-12-17T00:00:00+00:00 [running]> on host 2c1cd59afcc0
[2025-02-08T19:00:52.113+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Saleh' AIRFLOW_CTX_DAG_ID='account_dim_gen' AIRFLOW_CTX_TASK_ID='generate_account_dim_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-17T00:00:00+00:00'
[2025-02-08T19:00:52.114+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-08T19:00:52.132+0000] {logging_mixin.py:190} INFO - CSV file ./account_dim_large_data.csv with 50 row has been generated successfully!
[2025-02-08T19:00:52.132+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-08T19:00:52.141+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-08T19:00:52.141+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=account_dim_gen, task_id=generate_account_dim_data, run_id=scheduled__2024-12-17T00:00:00+00:00, execution_date=20241217T000000, start_date=20250208T190051, end_date=20250208T190052
[2025-02-08T19:00:52.198+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-08T19:00:52.206+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-08T20:40:57.275+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-08T20:40:57.299+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: account_dim_gen.generate_account_dim_data scheduled__2024-12-17T00:00:00+00:00 [queued]>
[2025-02-08T20:40:57.309+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: account_dim_gen.generate_account_dim_data scheduled__2024-12-17T00:00:00+00:00 [queued]>
[2025-02-08T20:40:57.309+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-02-08T20:40:57.325+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): generate_account_dim_data> on 2024-12-17 00:00:00+00:00
[2025-02-08T20:40:57.336+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1790) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-08T20:40:57.337+0000] {standard_task_runner.py:72} INFO - Started process 1814 to run task
[2025-02-08T20:40:57.336+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'account_dim_gen', 'generate_account_dim_data', 'scheduled__2024-12-17T00:00:00+00:00', '--job-id', '287', '--raw', '--subdir', 'DAGS_FOLDER/account_dim_gen.py', '--cfg-path', '/tmp/tmptk6vrwlg']
[2025-02-08T20:40:57.339+0000] {standard_task_runner.py:105} INFO - Job 287: Subtask generate_account_dim_data
[2025-02-08T20:40:57.395+0000] {task_command.py:467} INFO - Running <TaskInstance: account_dim_gen.generate_account_dim_data scheduled__2024-12-17T00:00:00+00:00 [running]> on host 7e959c1a2a8b
[2025-02-08T20:40:57.484+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Saleh' AIRFLOW_CTX_DAG_ID='account_dim_gen' AIRFLOW_CTX_TASK_ID='generate_account_dim_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-17T00:00:00+00:00'
[2025-02-08T20:40:57.488+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-08T20:40:57.515+0000] {logging_mixin.py:190} INFO - CSV file ./account_dim_large_data.csv with 50 row has been generated successfully!
[2025-02-08T20:40:57.516+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-08T20:40:57.539+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-08T20:40:57.541+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=account_dim_gen, task_id=generate_account_dim_data, run_id=scheduled__2024-12-17T00:00:00+00:00, execution_date=20241217T000000, start_date=20250208T204057, end_date=20250208T204057
[2025-02-08T20:40:57.596+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-08T20:40:57.613+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-08T20:40:57.617+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
