[2025-02-08T19:01:18.747+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-08T19:01:18.761+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: account_dim_gen.generate_account_dim_data scheduled__2025-01-30T00:00:00+00:00 [queued]>
[2025-02-08T19:01:18.774+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: account_dim_gen.generate_account_dim_data scheduled__2025-01-30T00:00:00+00:00 [queued]>
[2025-02-08T19:01:18.775+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-02-08T19:01:18.789+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): generate_account_dim_data> on 2025-01-30 00:00:00+00:00
[2025-02-08T19:01:18.800+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1091) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-08T19:01:18.802+0000] {standard_task_runner.py:72} INFO - Started process 1106 to run task
[2025-02-08T19:01:18.800+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'account_dim_gen', 'generate_account_dim_data', 'scheduled__2025-01-30T00:00:00+00:00', '--job-id', '146', '--raw', '--subdir', 'DAGS_FOLDER/account_dim_gen.py', '--cfg-path', '/tmp/tmp1xecnog3']
[2025-02-08T19:01:18.802+0000] {standard_task_runner.py:105} INFO - Job 146: Subtask generate_account_dim_data
[2025-02-08T19:01:18.853+0000] {task_command.py:467} INFO - Running <TaskInstance: account_dim_gen.generate_account_dim_data scheduled__2025-01-30T00:00:00+00:00 [running]> on host 2c1cd59afcc0
[2025-02-08T19:01:18.935+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Saleh' AIRFLOW_CTX_DAG_ID='account_dim_gen' AIRFLOW_CTX_TASK_ID='generate_account_dim_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-30T00:00:00+00:00'
[2025-02-08T19:01:18.936+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-08T19:01:18.956+0000] {logging_mixin.py:190} INFO - CSV file ./account_dim_large_data.csv with 50 row has been generated successfully!
[2025-02-08T19:01:18.957+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-08T19:01:18.968+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-08T19:01:18.968+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=account_dim_gen, task_id=generate_account_dim_data, run_id=scheduled__2025-01-30T00:00:00+00:00, execution_date=20250130T000000, start_date=20250208T190118, end_date=20250208T190118
[2025-02-08T19:01:19.061+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-08T19:01:19.079+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-08T19:01:19.082+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-08T20:42:39.687+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-08T20:42:39.702+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: account_dim_gen.generate_account_dim_data scheduled__2025-01-30T00:00:00+00:00 [queued]>
[2025-02-08T20:42:39.709+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: account_dim_gen.generate_account_dim_data scheduled__2025-01-30T00:00:00+00:00 [queued]>
[2025-02-08T20:42:39.710+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-02-08T20:42:39.722+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): generate_account_dim_data> on 2025-01-30 00:00:00+00:00
[2025-02-08T20:42:39.729+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'account_dim_gen', 'generate_account_dim_data', 'scheduled__2025-01-30T00:00:00+00:00', '--job-id', '390', '--raw', '--subdir', 'DAGS_FOLDER/account_dim_gen.py', '--cfg-path', '/tmp/tmplw9pgbze']
[2025-02-08T20:42:39.731+0000] {standard_task_runner.py:105} INFO - Job 390: Subtask generate_account_dim_data
[2025-02-08T20:42:39.731+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=310) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-08T20:42:39.732+0000] {standard_task_runner.py:72} INFO - Started process 315 to run task
[2025-02-08T20:42:39.767+0000] {task_command.py:467} INFO - Running <TaskInstance: account_dim_gen.generate_account_dim_data scheduled__2025-01-30T00:00:00+00:00 [running]> on host 86932746817d
[2025-02-08T20:42:39.827+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Saleh' AIRFLOW_CTX_DAG_ID='account_dim_gen' AIRFLOW_CTX_TASK_ID='generate_account_dim_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-30T00:00:00+00:00'
[2025-02-08T20:42:39.828+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-08T20:42:39.843+0000] {logging_mixin.py:190} INFO - CSV file ./account_dim_large_data.csv with 50 row has been generated successfully!
[2025-02-08T20:42:39.843+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-08T20:42:39.849+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-08T20:42:39.850+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=account_dim_gen, task_id=generate_account_dim_data, run_id=scheduled__2025-01-30T00:00:00+00:00, execution_date=20250130T000000, start_date=20250208T204239, end_date=20250208T204239
[2025-02-08T20:42:39.870+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-08T20:42:39.909+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-08T20:42:39.924+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
