[2025-02-08T19:01:05.900+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-08T19:01:05.915+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: account_dim_gen.generate_account_dim_data scheduled__2025-01-08T00:00:00+00:00 [queued]>
[2025-02-08T19:01:05.925+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: account_dim_gen.generate_account_dim_data scheduled__2025-01-08T00:00:00+00:00 [queued]>
[2025-02-08T19:01:05.926+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-02-08T19:01:05.942+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): generate_account_dim_data> on 2025-01-08 00:00:00+00:00
[2025-02-08T19:01:05.952+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=979) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-08T19:01:05.953+0000] {standard_task_runner.py:72} INFO - Started process 998 to run task
[2025-02-08T19:01:05.952+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'account_dim_gen', 'generate_account_dim_data', 'scheduled__2025-01-08T00:00:00+00:00', '--job-id', '124', '--raw', '--subdir', 'DAGS_FOLDER/account_dim_gen.py', '--cfg-path', '/tmp/tmpwssmlpo3']
[2025-02-08T19:01:05.954+0000] {standard_task_runner.py:105} INFO - Job 124: Subtask generate_account_dim_data
[2025-02-08T19:01:06.000+0000] {task_command.py:467} INFO - Running <TaskInstance: account_dim_gen.generate_account_dim_data scheduled__2025-01-08T00:00:00+00:00 [running]> on host 2c1cd59afcc0
[2025-02-08T19:01:06.081+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Saleh' AIRFLOW_CTX_DAG_ID='account_dim_gen' AIRFLOW_CTX_TASK_ID='generate_account_dim_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-08T00:00:00+00:00'
[2025-02-08T19:01:06.082+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-08T19:01:06.103+0000] {logging_mixin.py:190} INFO - CSV file ./account_dim_large_data.csv with 50 row has been generated successfully!
[2025-02-08T19:01:06.103+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-08T19:01:06.111+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-08T19:01:06.112+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=account_dim_gen, task_id=generate_account_dim_data, run_id=scheduled__2025-01-08T00:00:00+00:00, execution_date=20250108T000000, start_date=20250208T190105, end_date=20250208T190106
[2025-02-08T19:01:06.132+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-08T19:01:06.141+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-08T20:41:13.864+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-08T20:41:13.877+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: account_dim_gen.generate_account_dim_data scheduled__2025-01-08T00:00:00+00:00 [queued]>
[2025-02-08T20:41:13.885+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: account_dim_gen.generate_account_dim_data scheduled__2025-01-08T00:00:00+00:00 [queued]>
[2025-02-08T20:41:13.885+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-02-08T20:41:13.898+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): generate_account_dim_data> on 2025-01-08 00:00:00+00:00
[2025-02-08T20:41:13.908+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2043) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-08T20:41:13.909+0000] {standard_task_runner.py:72} INFO - Started process 2050 to run task
[2025-02-08T20:41:13.908+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'account_dim_gen', 'generate_account_dim_data', 'scheduled__2025-01-08T00:00:00+00:00', '--job-id', '344', '--raw', '--subdir', 'DAGS_FOLDER/account_dim_gen.py', '--cfg-path', '/tmp/tmpy5e5a4t0']
[2025-02-08T20:41:13.911+0000] {standard_task_runner.py:105} INFO - Job 344: Subtask generate_account_dim_data
[2025-02-08T20:41:13.947+0000] {task_command.py:467} INFO - Running <TaskInstance: account_dim_gen.generate_account_dim_data scheduled__2025-01-08T00:00:00+00:00 [running]> on host 7e959c1a2a8b
[2025-02-08T20:41:14.015+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Saleh' AIRFLOW_CTX_DAG_ID='account_dim_gen' AIRFLOW_CTX_TASK_ID='generate_account_dim_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-08T00:00:00+00:00'
[2025-02-08T20:41:14.016+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-08T20:41:14.032+0000] {logging_mixin.py:190} INFO - CSV file ./account_dim_large_data.csv with 50 row has been generated successfully!
[2025-02-08T20:41:14.032+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-08T20:41:14.039+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-08T20:41:14.040+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=account_dim_gen, task_id=generate_account_dim_data, run_id=scheduled__2025-01-08T00:00:00+00:00, execution_date=20250108T000000, start_date=20250208T204113, end_date=20250208T204114
[2025-02-08T20:41:14.083+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-08T20:41:14.098+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-08T20:41:14.100+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
