[2025-02-08T19:03:08.472+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-08T19:03:08.503+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2025-01-08T00:00:00+00:00 [queued]>
[2025-02-08T19:03:08.512+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2025-01-08T00:00:00+00:00 [queued]>
[2025-02-08T19:03:08.513+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-02-08T19:03:08.684+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): generate_customer_dim_data> on 2025-01-08 00:00:00+00:00
[2025-02-08T19:03:08.692+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1944) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-08T19:03:08.694+0000] {standard_task_runner.py:72} INFO - Started process 1977 to run task
[2025-02-08T19:03:08.697+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'customer_dim_generator', 'generate_customer_dim_data', 'scheduled__2025-01-08T00:00:00+00:00', '--job-id', '344', '--raw', '--subdir', 'DAGS_FOLDER/customer_dim_gen.py', '--cfg-path', '/tmp/tmpium8t8bi']
[2025-02-08T19:03:08.705+0000] {standard_task_runner.py:105} INFO - Job 344: Subtask generate_customer_dim_data
[2025-02-08T19:03:08.786+0000] {task_command.py:467} INFO - Running <TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2025-01-08T00:00:00+00:00 [running]> on host 2c1cd59afcc0
[2025-02-08T19:03:08.918+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Saleh' AIRFLOW_CTX_DAG_ID='customer_dim_generator' AIRFLOW_CTX_TASK_ID='generate_customer_dim_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-08T00:00:00+00:00'
[2025-02-08T19:03:08.919+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-08T19:03:08.948+0000] {logging_mixin.py:190} INFO - CSV file './customer_dim_large_data.csv' with 100 rows has been generated successfully.
[2025-02-08T19:03:08.950+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-08T19:03:08.964+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-08T19:03:08.964+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=customer_dim_generator, task_id=generate_customer_dim_data, run_id=scheduled__2025-01-08T00:00:00+00:00, execution_date=20250108T000000, start_date=20250208T190308, end_date=20250208T190308
[2025-02-08T19:03:08.999+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-08T19:03:09.022+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-08T19:03:09.028+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-08T20:40:56.064+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-08T20:40:56.094+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2025-01-08T00:00:00+00:00 [queued]>
[2025-02-08T20:40:56.105+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2025-01-08T00:00:00+00:00 [queued]>
[2025-02-08T20:40:56.106+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-02-08T20:40:56.125+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): generate_customer_dim_data> on 2025-01-08 00:00:00+00:00
[2025-02-08T20:40:56.138+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'customer_dim_generator', 'generate_customer_dim_data', 'scheduled__2025-01-08T00:00:00+00:00', '--job-id', '279', '--raw', '--subdir', 'DAGS_FOLDER/customer_dim_gen.py', '--cfg-path', '/tmp/tmpc_2buz6x']
[2025-02-08T20:40:56.142+0000] {standard_task_runner.py:105} INFO - Job 279: Subtask generate_customer_dim_data
[2025-02-08T20:40:56.145+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1756) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-08T20:40:56.146+0000] {standard_task_runner.py:72} INFO - Started process 1778 to run task
[2025-02-08T20:40:56.235+0000] {task_command.py:467} INFO - Running <TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2025-01-08T00:00:00+00:00 [running]> on host 7e959c1a2a8b
[2025-02-08T20:40:56.401+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Saleh' AIRFLOW_CTX_DAG_ID='customer_dim_generator' AIRFLOW_CTX_TASK_ID='generate_customer_dim_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-08T00:00:00+00:00'
[2025-02-08T20:40:56.403+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-08T20:40:56.435+0000] {logging_mixin.py:190} INFO - CSV file './customer_dim_large_data.csv' with 100 rows has been generated successfully.
[2025-02-08T20:40:56.436+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-08T20:40:56.446+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-08T20:40:56.446+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=customer_dim_generator, task_id=generate_customer_dim_data, run_id=scheduled__2025-01-08T00:00:00+00:00, execution_date=20250108T000000, start_date=20250208T204056, end_date=20250208T204056
[2025-02-08T20:40:56.492+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-08T20:40:56.505+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-08T20:43:38.922+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-08T20:43:38.938+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2025-01-08T00:00:00+00:00 [queued]>
[2025-02-08T20:43:38.946+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2025-01-08T00:00:00+00:00 [queued]>
[2025-02-08T20:43:38.947+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-02-08T20:43:38.962+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): generate_customer_dim_data> on 2025-01-08 00:00:00+00:00
[2025-02-08T20:43:38.972+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=804) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-08T20:43:38.973+0000] {standard_task_runner.py:72} INFO - Started process 817 to run task
[2025-02-08T20:43:38.972+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'customer_dim_generator', 'generate_customer_dim_data', 'scheduled__2025-01-08T00:00:00+00:00', '--job-id', '498', '--raw', '--subdir', 'DAGS_FOLDER/customer_dim_gen.py', '--cfg-path', '/tmp/tmpgzbbo3l6']
[2025-02-08T20:43:38.974+0000] {standard_task_runner.py:105} INFO - Job 498: Subtask generate_customer_dim_data
[2025-02-08T20:43:39.021+0000] {task_command.py:467} INFO - Running <TaskInstance: customer_dim_generator.generate_customer_dim_data scheduled__2025-01-08T00:00:00+00:00 [running]> on host 86932746817d
[2025-02-08T20:43:39.109+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Saleh' AIRFLOW_CTX_DAG_ID='customer_dim_generator' AIRFLOW_CTX_TASK_ID='generate_customer_dim_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-08T00:00:00+00:00'
[2025-02-08T20:43:39.110+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-08T20:43:39.132+0000] {logging_mixin.py:190} INFO - CSV file './customer_dim_large_data.csv' with 100 rows has been generated successfully.
[2025-02-08T20:43:39.132+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-08T20:43:39.141+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-08T20:43:39.142+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=customer_dim_generator, task_id=generate_customer_dim_data, run_id=scheduled__2025-01-08T00:00:00+00:00, execution_date=20250108T000000, start_date=20250208T204338, end_date=20250208T204339
[2025-02-08T20:43:39.230+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-08T20:43:39.250+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-08T20:43:39.254+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
